name: Build Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4

      - name: Build APK
        run: gradle :app:assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: apk-${{ github.ref_name }}
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
