name: Scan with Detekt

on:
  push:
    branches:
      - main
    paths:
      - 'app/config/detekt.yml'
      - 'app/src/main/java/**'
      - 'app/src/test/java/**'
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  security-events: write

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4

      - name: Run Detekt
        continue-on-error: true
        run: gradle :app:detekt

      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: app/build/reports/detekt/detekt.sarif
