name: Scan with Detekt

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

  workflow_dispatch:

env:
  DETEKT_VERSION: 1.23.4
  DETEKT_COMPOSE_VERSION: 0.3.8

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Detekt
        continue-on-error: true
        run: ./gradlew :app:detekt

      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: app/build/reports/detekt/detekt.sarif
